CREATE DATABASE ZEPTO_PROJECT;
USE ZEPTO_PROJECT;

DROP TABLE IF EXISTS ZEPTO;

CREATE TABLE ZEPTO(
SKU_ID SERIAL PRIMARY KEY,
CATEGORY VARCHAR(120),
NAME VARCHAR(150) NOT NULL,
MRP NUMERIC(8,2),
DISCOUNTPERCENT NUMERIC(5,2),
AVAILABLEQUANTITY INTEGER,
DISCOUNTSELLINGPRICE NUMERIC(8,2),
WEIGHTINGMS INTEGER,
OUTOFSTOCK BOOLEAN,
QUANTITY INTEGER
);
-- CREATED A TABLE AND IMPORTED THE DATA 
-- IN OUTOFSTOCK COLUMN 0 MEANS THEY ARE IN STOCK AND 1 MEANS THEY ARE OUT OF STOCK
-- DATA EXPLORATION

-- COUNTING ROWS
SELECT COUNT(*) FROM ZEPTO;
-- THERE ARE 3728 ROWS IN THIS DATA

-- DATA
SELECT * FROM ZEPTO 
LIMIT 10;

-- NULL VALUES
SELECT * FROM ZEPTO 
WHERE NAME IS NULL
OR CATEGORY IS NULL
OR MRP IS NULL
OR DISCOUNTPERCENT IS NULL
OR DISCOUNTSELLINGPRICE IS NULL
OR WEIGHTINGMS IS NULL
OR AVAILABLEQUANTITY IS NULL
OR OUTOFSTOCK IS NULL
OR QUANTITY IS NULL;
-- THERE ARE NO NULL VALUES IN THE DATA 

-- DIFFERENT PRODUCT CATEGORIES
SELECT DISTINCT CATEGORY
FROM ZEPTO 
ORDER BY CATEGORY;
-- THERE ARE 14 VARIATIES OF THE CATEGORIES 

-- PRODUCTS IN STOCK VS OUT OF STOCK 
SELECT OUTOFSTOCK,COUNT(SKU_ID) 
FROM ZEPTO 
GROUP BY OUTOFSTOCK;
-- 3275 PRODUCTS ARE IN STOCK AND 453 ARE OUT OF STOCK 

-- PRODUCT NAMES PRESENT MULTIPLE TIMES 
SELECT NAME,COUNT(SKU_ID) AS "NUMBER OF SKUs"
FROM ZEPTO 
GROUP BY NAME 
HAVING COUNT(SKU_ID)>1
ORDER BY COUNT(SKU_ID) DESC;
-- THERE ARE ALMOST 1000 DIFFERENT PRODUCTS WITH DIFFERENT VARIATIONS 

-- DATA CLEANING 

-- PRODUCTS WITH PRICE=0
SELECT * FROM ZEPTO 
WHERE MRP=0 OR DISCOUNTSELLINGPRICE=0;
-- THERE IS ONE PRODUCT WHICH HAS ZERO MRP . (3603 SKU_ID)
-- DELETING THAT ROW 
SET SQL_SAFE_UPDATES=0;
DELETE FROM ZEPTO 
WHERE MRP=0;
-- SUCCESFULLY DELETED THE 3603 ROW 

-- THE PRICES ARE IN THE PAISE FORM 
-- CONVERTING PAISE TO RUPEES 
UPDATE ZEPTO 
SET MRP=MRP/100.0, 
DISCOUNTSELLINGPRICE=DISCOUNTSELLINGPRICE/100.0;

SELECT MRP,DISCOUNTSELLINGPRICE FROM ZEPTO;
-- WE HAVE SUCCESSFULLY CHANGED THE PRICES FROM THE PAISE TO RUPEES

-- Q1: FIND THE TOP 10 BEST VALUE PRODUCTS BASED ON THE DISCOUNT PERCENTAGE. 
SELECT DISTINCT NAME,MRP,DISCOUNTPERCENT 
FROM ZEPTO
ORDER BY DISCOUNTPERCENT DESC 
LIMIT 10;
-- SOME WAFERS,MASALA,PASTA ARE THE BEST VALUE PRODUCTS BASED ON THE DISCOUNTS

-- Q2: WHAT ARE THE PRODUCTS WITH HIGH MRP BUT OUT OF STOCK 
SELECT MRP FROM ZEPTO 
ORDER BY MRP DESC 
LIMIT 10;
SELECT DISTINCT NAME,MRP 
FROM ZEPTO 
WHERE OUTOFSTOCK=1 AND MRP>300 
ORDER BY MRP DESC;
-- THERE ARE 4 PRODUCTS WITH HIGH MRP AND OUT OF STOCK 

-- Q3: CALCULATE ESTIMATED REVENUE FOR EACH CATEGORY 
SELECT CATEGORY,SUM(DISCOUNTSELLINGPRICE*AVAILABLEQUANTITY) AS REVENUE
FROM ZEPTO 
GROUP BY CATEGORY 
ORDER BY REVENUE DESC;
-- HIGHEST REVENUE GENERATING CATEGORIES ARE COOKING ESSENTIALS , MUNCHIES AND PERSONAL CARE

-- Q4: FIND ALL PRODUCTS WHERE MRP IS GREATER THAN RS.500 AND DISCOUNT IS LESS THAN 10%
SELECT DISTINCT NAME,MRP,DISCOUNTPERCENT
FROM ZEPTO 
WHERE MRP>500 AND DISCOUNTPERCENT<10
ORDER BY MRP DESC,DISCOUNTPERCENT DESC;
-- 39 PRODUCTS ARE MRP IS MORE THAN 500RS AND DISCOUNT IS LESS THAN 10% AND MOST OF THEM ARE WITH 0 DISCOUNT 

-- Q5: IDENTITY THE TOP 5 CATEGORIES OFFERING THE HIGHEST AVERAGE DISCOUNT PERCENTAGE 
SELECT CATEGORY,AVG(DISCOUNTPERCENT) AS AVG_DISC_PERC
FROM ZEPTO 
GROUP BY CATEGORY 
ORDER BY AVG_DISC_PERC DESC 
LIMIT 5;
-- THE TOP 5 HIGHEST DISOCUNT PROVIDING CATEGORIES ARE FRUITS AND VEGETABLES, MEATS,FISH AND EGGS , CHOCOLATES AND CANDIES , ICE CREAM AND DESSERTS , PACKAGED FOOD 

-- Q6: FIND THE PRICE PER GRAM FOR PRODUCTS ABOVE 100G AND SORT BY BEST VALUE
SELECT DISTINCT NAME,WEIGHTINGMS,DISCOUNTSELLINGPRICE,(DISCOUNTSELLINGPRICE/WEIGHTINGMS) AS PRICE_PER_GMS 
FROM ZEPTO 
WHERE WEIGHTINGMS>100 
ORDER BY PRICE_PER_GMS;
-- PRODUCTS LIKE COUGH DROPS AND SALT HAS LESS COST COMPARITIVELY

-- Q7: GROUP THE PRODUCTS INTO CATEGORIES LIKE LOW, MEDIUM ,BULK 
SELECT DISTINCT NAME,WEIGHTINGMS,
CASE WHEN WEIGHTINGMS<1000 THEN "LOW" 
	 WHEN WEIGHTINGMS<5000 THEN "MEDIUM"
     ELSE "BULK"
     END AS WEIGHT_CATEGORY
FROM ZEPTO ;
-- CATEGORISED PRODUCTS BY WEIGHTS INTO LOW,MEDIUM, BULK

-- Q8: WHAT IS THE TOTAL INVENTORY WEIGHT PER CATEGORY 
SELECT CATEGORY,SUM(WEIGHTINGMS*AVAILABLEQUANTITY) AS TOTAL_WEIGHT
FROM ZEPTO 
GROUP BY CATEGORY 
ORDER BY TOTAL_WEIGHT;
-- CATEGORIES BASED ON TOTAL INVENTORY WEIGHTS

-- Q9: Top revenue-contributing category
SELECT CATEGORY,SUM(DISCOUNTSELLINGPRICE*AVAILABLEQUANTITY) AS TOT_REVENUE
FROM ZEPTO 
GROUP BY CATEGORY 
ORDER BY TOT_REVENUE DESC
LIMIT 1;
-- COOKING ESSENTIALS CATEGORY CONTRIBUTES HIGHEST REVENUE OF AROUND 337131 

-- Q10: Top 5 products by profit margin 
SELECT DISTINCT NAME,((MRP-DISCOUNTSELLINGPRICE)/MRP)*100 AS PROFIT_MARGIN 
FROM ZEPTO 
ORDER BY PROFIT_MARGIN DESC 
LIMIT 5;  
-- DUKES WAFFY FAVOURED WAFFERES, RRO FRESH RICOTTA AND RRO MOZZARELLA PIZZA HAS GREAT PROFIT MARGIN AMONG ALL THE PRODUCTS 

-- Q11: Out-of-stock percentage by category 
SELECT CATEGORY,(SUM(OUTOFSTOCK)*100/COUNT(*)) AS PERC 
FROM ZEPTO 
GROUP BY CATEGORY 
ORDER BY PERC DESC;
-- THE BISCUITS AND DIARY,BREAD AND BATTER CATEGORY HAS GREATER PERCENTAGE OF OUT OF STOCK STATUS 

-- Q12: Variation in discount percentage 
SELECT CATEGORY ,STDDEV(DISCOUNTPERCENT) AS DISCOUNT_VARIATION 
FROM ZEPTO 
GROUP BY CATEGORY 
ORDER BY DISCOUNT_VARIATION DESC 
LIMIT 5;
-- THESE CATEGORIES HAVE HIGH VARIATION MAY HAVE INCONSISTENT DISCOUNT STRATEGIES 

-- Q13: Total inventory value per category
SELECT CATEGORY,SUM(MRP*AVAILABLEQUANTITY) AS TOT_MRP,SUM(DISCOUNTSELLINGPRICE*AVAILABLEQUANTITY) AS TOT_DISCOUNTED_VALUE 
FROM ZEPTO 
GROUP BY CATEGORY 
ORDER BY TOT_MRP DESC;
-- COOKING ESSENTIALS AND MUCHIES ARE TOP TOTAL INVENTORY CATEGORIES

-- Q14: slow-moving products (low sales & high availability)
SELECT DISTINCT NAME,CATEGORY,AVAILABLEQUANTITY,DISCOUNTSELLINGPRICE,OUTOFSTOCK 
FROM ZEPTO 
WHERE AVAILABLEQUANTITY>(SELECT AVG(AVAILABLEQUANTITY) FROM ZEPTO) AND OUTOFSTOCK=0 
ORDER BY AVAILABLEQUANTITY DESC 
LIMIT 10;
-- GODREJ AER POWER POCKET AND ORIGAMI GOOD KARMA PAPER SERVIETTES ARE SLOW MOVING PRODUCTS AND BOTH OF THEM ARE FROM THE HOME AND CLEANING CATEGORY 

-- Q15: restock priority score 
SELECT NAME,(DISCOUNTSELLINGPRICE*(AVAILABLEQUANTITY+1)) AS POTENTIAL_VALUE,
(CASE WHEN OUTOFSTOCK=1 THEN "HIGH" 
	  WHEN AVAILABLEQUANTITY<2 THEN "MEDIUM" 
      ELSE "LOW"
      END ) AS RESTOCK_PRIORITY 
FROM ZEPTO 
ORDER BY RESTOCK_PRIORITY DESC,POTENTIAL_VALUE DESC;
-- High-priority items with large potential value should be restocked first to prevent lost sales.